### ISSUE TITLE
is this repo open for open-source contribution?

### ISSUE THREAD

**Issue by ranggakd** [tunguz/TabularBenchmarks#6]
I wonder if there's a guideline to contribute to this repo via merged PRs like for example propose a good dataset for certain topic that has not been covered yet?
I would like to participate in such if I'm allowed.
Thanks!

**Comment by tunguz** [comment]
Yes, absolutely! I am still in process of cleaning the repo up and adding a bit more content, but the idea has been all along to open it up to **anyone's** contributions. Check out all the datasets that are available right now in the /datasets folder, and if there is something new that you'd like to add just make a PR!
